import type { MissionContent, DialogueNode, LearningBlock, ChallengeData } from '@/lib/types'

// ---------------------------------------------------------------------------
// Debt Asteroid Belt — 4 Missions
// Topic: The risks, realities, and career implications of AI-generated code
// ---------------------------------------------------------------------------

const fragileShipBriefing: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'Pilot, our long-range scans are picking up structural warnings across this asteroid field. The debris here is made of something familiar — AI-generated code that looked solid on the surface but shattered under real-world stress.',
  },
  {
    speaker: 'aria',
    text: 'When AI writes code, it draws from patterns in its training data. But training data gets stale, APIs change, and sometimes the AI simply hallucinates — confidently generating functions that reference libraries or methods that do not exist.',
  },
  {
    speaker: 'aria',
    text: 'I have isolated a module from one of these wrecks. Your job is to find the bugs before they find us. Ready your debugging tools, pilot.',
  },
]

const fragileShipLearning: LearningBlock[] = [
  {
    type: 'text',
    content:
      'AI models are trained on snapshots of the internet. When APIs evolve after that snapshot, the model keeps generating code for the old version. A function call that worked in 2023 might be deprecated or removed by 2025.',
  },
  {
    type: 'stat',
    content:
      'Up to 30% of AI-suggested API calls can reference deprecated or non-existent methods, according to studies on LLM code generation accuracy.',
    highlight: true,
  },
  {
    type: 'text',
    content:
      'Hallucinated APIs are only the beginning. AI-generated code frequently omits error handling, uses wrong variable names after refactoring context is lost, and introduces subtle off-by-one errors because it pattern-matches without truly understanding loop boundaries.',
  },
  {
    type: 'code',
    content:
      '// Common AI code issues:\n// 1. Deprecated APIs (fs.exists instead of fs.existsSync)\n// 2. Wrong variable references after copy-paste\n// 3. Off-by-one errors in loops\n// 4. Missing null/undefined checks',
  },
]

const fragileShipChallenge: ChallengeData = {
  type: 'debug',
  instructions:
    'This function was generated by an AI assistant to read configuration files and merge them. It contains 4 bugs typical of AI-generated code. Click on each buggy line to identify the issues.',
  data: {
    code: `const fs = require('fs');

async function mergeConfigs(configPaths) {
  const merged = {};

  for (let i = 0; i <= configPaths.length; i++) {
    const filePath = configPaths[i];

    if (fs.exists(filePath)) {
      const raw = fs.readFileSync(filePath, 'utf8');
      const parsed = JSON.parse(raw);

      for (const key of Object.keys(parsed)) {
        merged[key] = config[key] || parsed[key];
      }
    }
  }

  return merged;
}`,
    bugLines: [6, 9, 14],
    explanations: {
      6: 'Off-by-one error: using <= instead of < causes an out-of-bounds access on the last iteration, reading undefined from the array.',
      9: 'Deprecated API: fs.exists() was deprecated in Node.js v1.0.0 and removed as a synchronous call. Should use fs.existsSync() for synchronous checks, or fs.promises.access() for async.',
      14: 'Wrong variable name: references "config" which is undefined. Should be "merged" to check existing values before overwriting.',
    },
  },
  passingScore: 70,
}

const fragileShipDebrief: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'Well spotted, pilot. Every one of those bugs is something an AI would generate with total confidence. Deprecated APIs, wrong variable names, off-by-one errors — the code looks clean at a glance, but falls apart under scrutiny.',
  },
  {
    speaker: 'aria',
    text: 'This is why code review is not optional when working with AI. The machine writes plausible code, but plausible is not the same as correct. Your eyes are the last line of defense. Never trust — always verify.',
  },
]

// ---------------------------------------------------------------------------
// Mission 2: The Quality Crisis
// ---------------------------------------------------------------------------

const qualityCrisisBriefing: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'Pilot, I have been analyzing wreckage data from across the asteroid belt, and the numbers are alarming. Ships built entirely with AI-generated components are failing at rates far higher than expected.',
  },
  {
    speaker: 'aria',
    text: 'The 2025-2026 research data is in, and it paints a clear picture: AI-generated code introduces significantly more bugs, more security vulnerabilities, and more duplicated logic than human-written code.',
  },
  {
    speaker: 'aria',
    text: 'I have intercepted a code module with security vulnerabilities that are textbook AI-generated patterns. Let me walk you through the data, then you can hunt down the flaws.',
  },
]

const qualityCrisisLearning: LearningBlock[] = [
  {
    type: 'stat',
    content:
      'AI-generated code contains 1.75x more bugs than human-written code on average, according to large-scale analysis of production codebases in 2025.',
    highlight: true,
  },
  {
    type: 'stat',
    content:
      'Security is even worse: AI-generated code shows 2.74x more XSS (cross-site scripting) vulnerabilities. The AI copies patterns that look right but skip critical sanitization steps.',
    highlight: true,
  },
  {
    type: 'stat',
    content:
      'Code cloning — copying the same logic into multiple places instead of abstracting it — is 4x more common in AI-generated code. This creates maintenance nightmares as every clone must be updated independently.',
    highlight: true,
  },
  {
    type: 'text',
    content:
      'Why does this happen? AI models optimize for "looks correct" rather than "is correct." They lack project-wide awareness, so they cannot see that similar code already exists elsewhere. They default to the most common pattern in their training data, even when that pattern has known security flaws.',
  },
]

// NOTE: The code below intentionally contains security vulnerabilities (XSS via
// innerHTML, SQL injection, hardcoded credentials, missing validation) as an
// educational exercise. Students must identify these bugs in the debug mini-game.
const qualityCrisisChallenge: ChallengeData = {
  type: 'debug',
  instructions:
    'This AI-generated code handles user input for a web application. It contains 4 security vulnerabilities typical of AI-written code. Find them all before they reach production.',
  data: {
    code: [
      'function renderUserProfile(user) {',
      "  const container = document.getElementById('profile');",
      '',
      "  container.innerHTML = '<h1>' + user.displayName + '</h1>';",
      '',
      '  const query = "SELECT * FROM posts WHERE author = \'" + user.id + "\'";',
      "  fetch('/api/query', { method: 'POST', body: query });",
      '',
      "  const API_KEY = 'sk-proj-abc123def456';",
      "  fetch('/api/data', {",
      "    headers: { 'Authorization': 'Bearer ' + API_KEY }",
      '  });',
      '',
      '  const age = parseInt(user.age);',
      '  if (age > 0) {',
      "    container.innerHTML += '<p>Age: ' + age + '</p>';",
      '  }',
      '}',
    ].join('\n'),
    bugLines: [4, 6, 9, 14],
    explanations: {
      4: 'XSS vulnerability: Using innerHTML with unsanitized user input (user.displayName) allows script injection. Use textContent or sanitize the input first.',
      6: 'SQL injection: Building SQL queries with string concatenation allows attackers to inject malicious SQL. Use parameterized queries or an ORM instead.',
      9: 'Hardcoded credentials: API keys should never appear in client-side code. Use environment variables and server-side proxies to protect secrets.',
      14: 'Missing input validation: parseInt without a radix parameter and no NaN check. The user.age field is not validated — could be any string. Should use parseInt(user.age, 10) and check isNaN().',
    },
  },
  passingScore: 70,
}

const qualityCrisisDebrief: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'Every one of those vulnerabilities is something an AI would generate without hesitation. It has seen innerHTML used millions of times in training data, and most of those examples skip sanitization. The AI simply reproduces the most common pattern.',
  },
  {
    speaker: 'aria',
    text: 'Security awareness cannot be outsourced to AI. You need to know what XSS, SQL injection, and credential exposure look like — because the AI does not flag its own mistakes. Your expertise is the shield that protects real users.',
  },
]

// ---------------------------------------------------------------------------
// Mission 3: Your Career in the AI Era
// ---------------------------------------------------------------------------

const careerBriefing: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'Pilot, we are picking up transmissions from the employment sector of the belt. The signals tell a complicated story — some frequencies are fading while entirely new ones are emerging.',
  },
  {
    speaker: 'aria',
    text: 'AI tools are reshaping what it means to be a developer. Junior roles are shifting, new specializations are appearing, and the skills that matter most are evolving rapidly.',
  },
  {
    speaker: 'aria',
    text: 'Let me brief you on the landscape. Understanding these shifts is not optional — it is survival.',
  },
]

const careerLearning: LearningBlock[] = [
  {
    type: 'stat',
    content:
      'Junior developer hiring has dropped 9-10% since AI coding tools became widespread. Companies are using AI to handle tasks that were traditionally assigned to entry-level engineers.',
    highlight: true,
  },
  {
    type: 'text',
    content:
      'But the picture is not all negative. New roles are emerging: AI integration engineers, prompt engineers, agent architects, and AI safety specialists. The developers who learn to work with AI tools effectively are finding themselves more productive and more valuable.',
  },
  {
    type: 'text',
    content:
      'The skills that matter most now are shifting. Pure syntax knowledge is less important when AI can write boilerplate. What matters more: system design, debugging intuition, security awareness, understanding trade-offs, and the ability to evaluate AI output critically.',
  },
  {
    type: 'text',
    content:
      'The "10x developer" myth is becoming reality — but not because of raw coding speed. Developers who can effectively orchestrate AI tools, review AI output, and integrate AI-generated components into robust systems are genuinely multiplying their output.',
  },
]

const careerChallenge: ChallengeData = {
  type: 'dialogue',
  instructions:
    'ARIA is acting as your career counselor. Answer her questions about navigating the AI era to demonstrate your understanding of which skills and strategies will keep you relevant.',
  data: {
    nodes: [
      {
        speaker: 'aria',
        text: 'A junior developer asks you: "Should I even learn to code if AI can write it for me?" What is your best advice?',
        choices: [
          {
            text: 'No, focus on learning prompt engineering instead — coding is becoming obsolete.',
            correct: false,
            response:
              'Coding is not becoming obsolete — it is becoming augmented. Without understanding what the code does, you cannot evaluate, debug, or improve AI output. Prompt engineering alone is not enough.',
          },
          {
            text: 'Yes, learn to code deeply. AI makes good developers better, but it cannot replace understanding.',
            correct: true,
            response:
              'Exactly right. AI amplifies existing skill. A developer who understands architecture, debugging, and system design can use AI to move 5x faster. A non-developer using AI hits a wall the moment something breaks.',
          },
          {
            text: 'Only learn the basics — AI will handle the complex parts.',
            correct: false,
            response:
              'The complex parts are exactly where AI struggles most. Architecture decisions, security reviews, and debugging subtle issues all require deep understanding that AI cannot provide reliably.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'Which skill becomes MORE valuable as AI coding tools improve?',
        choices: [
          {
            text: 'Memorizing language syntax and API signatures.',
            correct: false,
            response:
              'Syntax memorization is exactly what AI handles well. This skill becomes less important, not more. Focus on what AI cannot do.',
          },
          {
            text: 'The ability to critically evaluate and debug AI-generated code.',
            correct: true,
            response:
              'Precisely. As more code is AI-generated, the ability to spot bugs, security flaws, and architectural problems in that code becomes the critical bottleneck. This is the skill that keeps humans essential.',
          },
          {
            text: 'Typing speed and code output volume.',
            correct: false,
            response:
              'AI already generates code faster than any human can type. Raw output speed is not the differentiator — quality of judgment is.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'A company is hiring for a new role: "AI Integration Engineer." What would you expect this role to focus on?',
        choices: [
          {
            text: 'Writing prompts for ChatGPT all day.',
            correct: false,
            response:
              'While prompts are part of it, an AI Integration Engineer does much more — they design systems that incorporate AI components reliably, handle failure modes, and ensure quality at scale.',
          },
          {
            text: 'Designing systems that orchestrate AI tools, handle their failures, and integrate their output into production software.',
            correct: true,
            response:
              'Spot on. This role is about the architecture around AI — how to make AI components reliable, how to handle their inevitable failures, and how to integrate them into systems that real users depend on.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'Junior dev hiring dropped 9-10%. What is the best response for someone entering the field?',
        choices: [
          {
            text: 'Give up on software engineering and switch to a different field.',
            correct: false,
            response:
              'The field is not shrinking — it is transforming. Software is more important than ever. The entry path is changing, but the destination is more exciting than before.',
          },
          {
            text: 'Learn AI tools deeply AND build strong fundamentals. Position yourself as someone who can do what AI cannot do alone.',
            correct: true,
            response:
              'That is the winning strategy. Companies still need humans who understand systems deeply. If you combine strong fundamentals with AI fluency, you become the kind of developer every team wants.',
          },
          {
            text: 'Only apply to companies that have banned AI tools.',
            correct: false,
            response:
              'Avoiding AI tools is not a viable long-term strategy. Virtually every software company will adopt AI in some form. Learning to work with these tools is essential.',
          },
        ],
      },
    ] as DialogueNode[],
  },
  passingScore: 70,
}

const careerDebrief: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'The AI era is not the end of software engineering — it is a transformation. The developers who thrive will be the ones who see AI as a power multiplier, not a replacement.',
  },
  {
    speaker: 'aria',
    text: 'Keep building your fundamentals, pilot. The deeper your understanding, the more effectively you can wield these tools. Continuous learning is not just a nice idea — it is your career insurance policy.',
  },
]

// ---------------------------------------------------------------------------
// Mission 4: The Case for Expertise
// ---------------------------------------------------------------------------

const expertiseBriefing: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'Pilot, I have been tracking an interesting signal — a transmission from Andrej Karpathy, one of the original pioneers of the term "vibe coding." His journey tells us something important about where this field is heading.',
  },
  {
    speaker: 'aria',
    text: 'In early 2025, Karpathy coined the term "vibe coding" — writing software by describing what you want in natural language and letting the AI handle the implementation. He called it "the most fun way to code."',
  },
  {
    speaker: 'aria',
    text: 'But the story did not end there. Within a year, Karpathy and the broader community evolved from casual vibe coding to what they call "agentic engineering" — a discipline that demands deep expertise. Let me show you why.',
  },
]

const expertiseLearning: LearningBlock[] = [
  {
    type: 'text',
    content:
      'In February 2025, Karpathy tweeted: "There is a new kind of coding I call vibe coding, where you fully give in to the vibes, embrace exponentials, and forget that the code even exists." It captured the excitement of a new paradigm.',
  },
  {
    type: 'text',
    content:
      'By 2026, the field matured significantly. Practitioners discovered that vibe coding alone hit a ceiling — projects grew complex, bugs multiplied, and AI-generated code needed expert oversight. The community shifted toward structured practices: CLAUDE.md files, memory systems, systematic review workflows.',
  },
  {
    type: 'text',
    content:
      'Here is the key insight: expertise does not become less valuable when AI tools get better. It becomes MORE valuable. A senior architect using AI tools can design, build, and ship systems that would have taken an entire team months. But only because they understand what the AI is producing.',
  },
  {
    type: 'stat',
    content:
      'Developers with 5+ years of experience report 3-4x greater productivity gains from AI tools compared to those with less than 1 year of experience. Expertise is the multiplier.',
    highlight: true,
  },
]

const expertiseChallenge: ChallengeData = {
  type: 'dialogue',
  instructions:
    'ARIA tests your understanding of why deep expertise enhances AI tools rather than being replaced by them. Choose wisely — this knowledge will shape your journey in Act 2.',
  data: {
    nodes: [
      {
        speaker: 'aria',
        text: 'Karpathy coined "vibe coding" in 2025. A year later, he and others evolved toward "agentic engineering." Why did this shift happen?',
        choices: [
          {
            text: 'AI tools got worse over time, so people went back to manual coding.',
            correct: false,
            response:
              'AI tools actually got significantly better. The shift happened because practitioners realized that more powerful tools require more expertise to wield effectively, not less.',
          },
          {
            text: 'As projects grew in complexity, practitioners discovered that casual vibe coding could not scale without deeper engineering discipline and expertise.',
            correct: true,
            response:
              'Exactly. Simple prototypes worked great with pure vibe coding. But production systems, security requirements, and complex architectures demanded the structured practices that come from deep engineering knowledge.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'A developer says: "AI will make expertise obsolete — anyone can build anything now." How would you respond?',
        choices: [
          {
            text: 'They are right — in five years, no one will need to understand code.',
            correct: false,
            response:
              'History shows the opposite pattern. Every time tools get more powerful — from assembly to high-level languages to frameworks — the ceiling rises but expertise becomes more important, not less.',
          },
          {
            text: 'AI lowers the floor but raises the ceiling. Anyone can build a prototype, but expertise determines whether it survives contact with real users.',
            correct: true,
            response:
              'Well said. AI democratizes the starting line, but the finish line — production quality, security, scalability, maintainability — still requires deep understanding. The gap between prototype and production is where expertise lives.',
          },
          {
            text: 'They are completely wrong — AI tools are useless without a CS degree.',
            correct: false,
            response:
              'That goes too far in the other direction. AI tools genuinely enable people without formal training to build useful software. The truth is in the middle — AI expands who can build, but expertise determines how well.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'Why do experienced developers get 3-4x more productivity gains from AI tools than beginners?',
        choices: [
          {
            text: 'They type faster and can use keyboard shortcuts better.',
            correct: false,
            response:
              'It has nothing to do with typing speed. The advantage is cognitive — experienced developers know what to ask for, can evaluate the output, and can guide the AI toward correct solutions.',
          },
          {
            text: 'They know what good code looks like, so they can prompt more precisely, catch AI mistakes faster, and make better architectural decisions about what to accept or reject.',
            correct: true,
            response:
              'Precisely. Expertise is the filter that separates good AI output from dangerous AI output. Experienced developers waste less time on dead ends because they recognize problems the AI introduces before those problems compound.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'What does the evolution from "vibe coding" to "agentic engineering" tell us about the future of software development?',
        choices: [
          {
            text: 'AI was a fad and everyone is going back to traditional development.',
            correct: false,
            response:
              'Not at all. The evolution shows AI tools becoming MORE central to development, not less. But the way we use them is maturing from casual prompting to disciplined engineering practices.',
          },
          {
            text: 'The tools are maturing, and so must our practices. The future belongs to developers who combine deep expertise with mastery of AI tooling — that is agentic engineering.',
            correct: true,
            response:
              'That is the core lesson. The best developers in the AI era will not be those who ignore AI or those who blindly trust it. They will be the ones who use deep expertise to direct AI tools with precision and judgment.',
          },
        ],
      },
      {
        speaker: 'aria',
        text: 'You are about to enter Act 2 of your journey, where you will learn about AI agents. What mindset should you bring?',
        choices: [
          {
            text: 'Let the AI agents handle everything — sit back and supervise.',
            correct: false,
            response:
              'Passive supervision is not enough. Agents need skilled operators who understand what they are doing, can course-correct when they go wrong, and can design the systems they operate within.',
          },
          {
            text: 'Combine curiosity about new tools with commitment to deep understanding. Use AI to amplify your expertise, not replace your learning.',
            correct: true,
            response:
              'That is the mindset of an agentic engineer. Curiosity drives exploration, expertise drives quality, and the combination drives innovation. You are ready for what comes next, pilot.',
          },
        ],
      },
    ] as DialogueNode[],
  },
  passingScore: 70,
}

const expertiseDebrief: DialogueNode[] = [
  {
    speaker: 'aria',
    text: 'You have navigated the Debt Asteroid Belt, pilot. You have seen the risks of AI-generated code — the bugs, the security holes, the career shifts. But you have also seen the opportunity: expertise makes these tools extraordinary.',
  },
  {
    speaker: 'aria',
    text: 'The journey from vibe coding to agentic engineering mirrors your own journey through this game. You started by learning to talk to AI. Now you understand why that is just the beginning.',
  },
  {
    speaker: 'aria',
    text: 'Ahead lies Act 2. MCP Station, Agent Academy, and the Framework Nebula await. You are ready for something bigger, pilot. The agents await.',
  },
]

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const debtBeltContent: Record<string, MissionContent> = {
  'debt-belt-m1': {
    briefing: fragileShipBriefing,
    learning: fragileShipLearning,
    challenge: fragileShipChallenge,
    debrief: fragileShipDebrief,
  },
  'debt-belt-m2': {
    briefing: qualityCrisisBriefing,
    learning: qualityCrisisLearning,
    challenge: qualityCrisisChallenge,
    debrief: qualityCrisisDebrief,
  },
  'debt-belt-m3': {
    briefing: careerBriefing,
    learning: careerLearning,
    challenge: careerChallenge,
    debrief: careerDebrief,
  },
  'debt-belt-m4': {
    briefing: expertiseBriefing,
    learning: expertiseLearning,
    challenge: expertiseChallenge,
    debrief: expertiseDebrief,
  },
}
